// Compiles the Rust kernel to WASM and inlines it as base64 into a TS module,
// so the core loads with no file/fetch plumbing in any environment.
//
//   node scripts/build-wasm.mjs        (expects the .wasm already built)
//   npm run build:wasm                 (cargo build + this script)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const wasmPath = join(
  root,
  "native/turboquant/target/wasm32-unknown-unknown/release/turboquant.wasm"
);

const bytes = readFileSync(wasmPath);
const b64 = bytes.toString("base64");
const out = `// AUTO-GENERATED by scripts/build-wasm.mjs — do not edit by hand.
// turboquant.wasm (${bytes.length} bytes) inlined as base64 so the core loads
// synchronously in Node, browsers, and Tauri with zero file/fetch plumbing.
export const WASM_BASE64 =
  "${b64}";
`;
writeFileSync(join(root, "src/vector/turboquant-wasm.ts"), out);
console.log(`inlined ${bytes.length} bytes -> src/vector/turboquant-wasm.ts`);
